// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/leads": {
    params: {};
  };
  "/leads/:id": {
    params: {
      "id": string;
    };
  };
  "/products": {
    params: {};
  };
  "/products/:id": {
    params: {
      "id": string;
    };
  };
  "/posts": {
    params: {};
  };
  "/posts/:id": {
    params: {
      "id": string;
    };
  };
  "/content": {
    params: {};
  };
  "/b2b": {
    params: {};
  };
  "/testimonials": {
    params: {};
  };
  "/nav": {
    params: {};
  };
  "/templates": {
    params: {};
  };
  "/media": {
    params: {};
  };
  "/tracking": {
    params: {};
  };
  "/seo": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/outbox": {
    params: {};
  };
  "/audit": {
    params: {};
  };
  "/categories": {
    params: {};
  };
  "/faq": {
    params: {};
  };
  "/redirects": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/leads" | "/leads/:id" | "/products" | "/products/:id" | "/posts" | "/posts/:id" | "/content" | "/b2b" | "/testimonials" | "/nav" | "/templates" | "/media" | "/tracking" | "/seo" | "/settings" | "/users" | "/outbox" | "/audit" | "/categories" | "/faq" | "/redirects";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/shell.tsx": {
    id: "routes/shell";
    page: "/" | "/leads" | "/leads/:id" | "/products" | "/products/:id" | "/posts" | "/posts/:id" | "/content" | "/b2b" | "/testimonials" | "/nav" | "/templates" | "/media" | "/tracking" | "/seo" | "/settings" | "/users" | "/outbox" | "/audit" | "/categories" | "/faq" | "/redirects";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/";
  };
  "routes/leads.tsx": {
    id: "routes/leads";
    page: "/leads";
  };
  "routes/lead-detail.tsx": {
    id: "routes/lead-detail";
    page: "/leads/:id";
  };
  "routes/products.tsx": {
    id: "routes/products";
    page: "/products";
  };
  "routes/product-editor.tsx": {
    id: "routes/product-editor";
    page: "/products/:id";
  };
  "routes/posts.tsx": {
    id: "routes/posts";
    page: "/posts";
  };
  "routes/post-editor.tsx": {
    id: "routes/post-editor";
    page: "/posts/:id";
  };
  "routes/content.tsx": {
    id: "routes/content";
    page: "/content";
  };
  "routes/b2b.tsx": {
    id: "routes/b2b";
    page: "/b2b";
  };
  "routes/testimonials.tsx": {
    id: "routes/testimonials";
    page: "/testimonials";
  };
  "routes/nav.tsx": {
    id: "routes/nav";
    page: "/nav";
  };
  "routes/templates.tsx": {
    id: "routes/templates";
    page: "/templates";
  };
  "routes/media.tsx": {
    id: "routes/media";
    page: "/media";
  };
  "routes/tracking.tsx": {
    id: "routes/tracking";
    page: "/tracking";
  };
  "routes/seo.tsx": {
    id: "routes/seo";
    page: "/seo";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/users.tsx": {
    id: "routes/users";
    page: "/users";
  };
  "routes/outbox.tsx": {
    id: "routes/outbox";
    page: "/outbox";
  };
  "routes/audit.tsx": {
    id: "routes/audit";
    page: "/audit";
  };
  "routes/categories.tsx": {
    id: "routes/categories";
    page: "/categories";
  };
  "routes/faq.tsx": {
    id: "routes/faq";
    page: "/faq";
  };
  "routes/redirects.tsx": {
    id: "routes/redirects";
    page: "/redirects";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/shell": typeof import("./app/routes/shell.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/leads": typeof import("./app/routes/leads.tsx");
  "routes/lead-detail": typeof import("./app/routes/lead-detail.tsx");
  "routes/products": typeof import("./app/routes/products.tsx");
  "routes/product-editor": typeof import("./app/routes/product-editor.tsx");
  "routes/posts": typeof import("./app/routes/posts.tsx");
  "routes/post-editor": typeof import("./app/routes/post-editor.tsx");
  "routes/content": typeof import("./app/routes/content.tsx");
  "routes/b2b": typeof import("./app/routes/b2b.tsx");
  "routes/testimonials": typeof import("./app/routes/testimonials.tsx");
  "routes/nav": typeof import("./app/routes/nav.tsx");
  "routes/templates": typeof import("./app/routes/templates.tsx");
  "routes/media": typeof import("./app/routes/media.tsx");
  "routes/tracking": typeof import("./app/routes/tracking.tsx");
  "routes/seo": typeof import("./app/routes/seo.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/users": typeof import("./app/routes/users.tsx");
  "routes/outbox": typeof import("./app/routes/outbox.tsx");
  "routes/audit": typeof import("./app/routes/audit.tsx");
  "routes/categories": typeof import("./app/routes/categories.tsx");
  "routes/faq": typeof import("./app/routes/faq.tsx");
  "routes/redirects": typeof import("./app/routes/redirects.tsx");
};