// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/proizvodi": {
    params: {};
  };
  "/proizvodi/:slug": {
    params: {
      "slug": string;
    };
  };
  "/za-biznis": {
    params: {};
  };
  "/soveti": {
    params: {};
  };
  "/soveti/:slug": {
    params: {
      "slug": string;
    };
  };
  "/za-nas": {
    params: {};
  };
  "/kontakt": {
    params: {};
  };
  "/blagodarime": {
    params: {};
  };
  "/pravni/:slug": {
    params: {
      "slug": string;
    };
  };
  "/sitemap.xml": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/proizvodi" | "/proizvodi/:slug" | "/za-biznis" | "/soveti" | "/soveti/:slug" | "/za-nas" | "/kontakt" | "/blagodarime" | "/pravni/:slug" | "/sitemap.xml" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/catalog.tsx": {
    id: "routes/catalog";
    page: "/proizvodi";
  };
  "routes/product.tsx": {
    id: "routes/product";
    page: "/proizvodi/:slug";
  };
  "routes/b2b.tsx": {
    id: "routes/b2b";
    page: "/za-biznis";
  };
  "routes/blog.tsx": {
    id: "routes/blog";
    page: "/soveti";
  };
  "routes/post.tsx": {
    id: "routes/post";
    page: "/soveti/:slug";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/za-nas";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/kontakt";
  };
  "routes/thank-you.tsx": {
    id: "routes/thank-you";
    page: "/blagodarime";
  };
  "routes/legal.tsx": {
    id: "routes/legal";
    page: "/pravni/:slug";
  };
  "routes/sitemap.tsx": {
    id: "routes/sitemap";
    page: "/sitemap.xml";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/catalog": typeof import("./app/routes/catalog.tsx");
  "routes/product": typeof import("./app/routes/product.tsx");
  "routes/b2b": typeof import("./app/routes/b2b.tsx");
  "routes/blog": typeof import("./app/routes/blog.tsx");
  "routes/post": typeof import("./app/routes/post.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/thank-you": typeof import("./app/routes/thank-you.tsx");
  "routes/legal": typeof import("./app/routes/legal.tsx");
  "routes/sitemap": typeof import("./app/routes/sitemap.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};