// Downloads the design fonts (cyrillic+latin) from Google Fonts as self-hosted woff2
// and generates apps/web/app/fonts.css. Run once: node scripts/fetch-fonts.mjs
// (self-hosting keeps runtime free of the Google CDN — CLAUDE.md §10.3).
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';
const OUT_DIR = join(process.cwd(), 'apps/web/public/fonts');
const CSS_OUT = join(process.cwd(), 'apps/web/app/fonts.css');

const FAMILIES = [
  { name: 'Manrope', axis: 'wght@400;500;600;700;800' },
  { name: 'Unbounded', axis: 'wght@400;500;600;700' },
  { name: 'Oswald', axis: 'wght@300;400;500;600;700' },
  { name: 'Onest', axis: 'wght@400;500;600;700' },
  { name: 'JetBrains+Mono', axis: 'wght@400;500;700' },
];

const KEEP_SUBSETS = ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext'];

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  let css = '/* Auto-generated by scripts/fetch-fonts.mjs — self-hosted design fonts. */\n';
  const seen = new Set();

  for (const fam of FAMILIES) {
    const url = `https://fonts.googleapis.com/css2?family=${fam.name}:${fam.axis}&display=swap`;
    const res = await fetch(url, { headers: { 'User-Agent': UA } });
    const text = await res.text();

    // Each @font-face block is preceded by a comment naming the subset.
    const blocks = text.split('/* ').slice(1);
    for (const block of blocks) {
      const subset = block.slice(0, block.indexOf(' ')).trim();
      if (!KEEP_SUBSETS.includes(subset)) continue;
      const face = '@font-face' + block.slice(block.indexOf('@font-face') + 10);

      const srcMatch = face.match(/src:\s*url\((https:[^)]+\.woff2)\)/);
      if (!srcMatch) continue;
      const remoteUrl = srcMatch[1];
      const weightMatch = face.match(/font-weight:\s*(\d+)/);
      const weight = weightMatch ? weightMatch[1] : '400';
      const famSlug = fam.name.toLowerCase().replace('+', '-');
      const fileName = `${famSlug}-${weight}-${subset}.woff2`;

      if (!seen.has(fileName)) {
        seen.add(fileName);
        const bin = await fetch(remoteUrl, { headers: { 'User-Agent': UA } }).then((r) => r.arrayBuffer());
        await writeFile(join(OUT_DIR, fileName), Buffer.from(bin));
      }
      css += face.replace(remoteUrl, `/fonts/${fileName}`).trim() + '\n';
    }
    // eslint-disable-next-line no-console
    console.log(`✔ ${fam.name}`);
  }

  await writeFile(CSS_OUT, css);
  // eslint-disable-next-line no-console
  console.log(`Wrote ${seen.size} woff2 files + fonts.css`);
}

main().catch((e) => {
  // eslint-disable-next-line no-console
  console.error(e);
  process.exit(1);
});
